### ISSUE TITLE
Nick changes cause the stats page to become unreadable

### ISSUE THREAD

**Issue by scrib-bler** [snkenjoi/Nibblr#2]
Every nick that isn't 'nibblr' gets added to the logs, regardless of total lines. This also includes nibblr logging its own messages when we change his name via ~nick.

Suggestions: log by vhost, rather than nick, this will cut down on overall nicks, and keep logs consistent when people decide to change their name to CUNTFUCK for 15 minutes.
This will also stop nibblr logging his own messages when ~nick abuse inevitably occurs.

May also be worth implementing a minimum line count for inclusion on the stats page (10,20,50,100,etc). This will stop the page getting filled up with Guestxxxxx entries.

Could also be worth ignoring any user with qwebirc@*

Picture of current stats page after ~nick command happy fun times occured: http://i.imgur.com/lQdN7VS.png

**Comment by kirjavascript** [comment]
only lists top 30 spammers now
