### ISSUE TITLE
YouTube command

### ISSUE THREAD

**Issue by ShreddyMarz** [snkenjoi/Nibblr#3]
could you make the URL parsing for youtube display certain stats about videos, please?

ex: <nibblr> YouTube :: Lock-Up_ RAW Booty Warrior FLEECE JOHNSON :: Duration: 03:06 :: Views: 3,857,151 uploaded by FonkDoktaVidz :: 10,537 likes :: 1,086 dislikes :: 0 favorites

**Comment by kirjavascript** [comment]
`~youtube` is now using the same api as `~google` for better search results and cannot get this information
