### ISSUE TITLE
slots jackpot 0dayz

### ISSUE THREAD

**Issue by scrib-bler** [snkenjoi/Nibblr#9]
we hax0red ur gibson.

if you ~reset right after someone wins a jackpot, the jackpot will be preserved once the bot reconnects, and the person that won gets to keep their winnings.

> [23:56:40] <Scribbler> ~slots
> [23:56:40] <slots> [SLOT-MACHINE] Current Jackpot: €340  :::  Rolling the wheels.
> [23:56:41] <slots>  CHERRY  CHERRY  CHERRY 
> [23:56:41] **<slots>   J  A  C  K  P  O  T    !!! Scribbler just won €340 !**
> [23:56:41] <slots> **Scribbler has €4600** 
> [23:56:43] <Scribbler> ~reset
> [23:56:43] <-- slots (~eternium@Rizon-58D6F2FE.us-west-2.compute.amazonaws.com) has quit **(Remote host closed the connection)**
> [23:56:45] --> nibblr (~eternium@Rizon-58D6F2FE.us-west-2.compute.amazonaws.com) has **joined #8BitVape**
> [23:56:45] **\* Mode #8BitVape +ao nibblr nibblr by [^_^]
> [23:56:48] <Scribbler> ~slotstats
> [23:56:48] <nibblr> slots points: Banks: 95 TzmFen: 445 **Scribbler: 4600** Shreddy: 4875 cr0sis: 2606 megaproxy: 3208 Kirjava: 4478 barf: 1028 Budrick: 3212 oh_dear_god_the_buffer: 96 kingchris: 405 cr0hypnol: 99 sofakingchris: 310 **$jackpot: 340** steve_is_awesome: 99 Scooby: 188 eyebrowse: 238 stevesucks: 97 PkMnTrainerJow: 99 jackpot: 99 ScribblersMom: 99 hollow_Shreddy: 99 Scroobler: 99 Notcr0sis: 103
> [23:56:48] <nibblr> cr0sis_: 99 Robsssss: 99 Shreddy2: 87 vanillazai: 75 Guest20017: 97 cr17sis: 91 ScribbIer: 78 i_cant_make_it_stop: 97 shawn: 83 b4rf: 82 Shredroid: 97 homer: 98 caylo: 68 Robs: 15 ndk: -17
> [23:56:54] <Scribbler> there you go

**Comment by kirjavascript** [comment]
damnit. was just an oversight, should be fixed
